.travis.yml
Pipfile
app.py

This is the first edition of new code in this repo. This PR sets up the minimum of `.travis.yml`, a brand new `Pipfile` to start with and running the `app.py`.
In order to test the app.py changes, run:
```python
python3 app.py """To start the server"""
curl http://127.0.0.1:5000/ping """To call /ping endpoint"""
```

setup app.py

---

README.md
ros/.env.example

This PR adds a `.env.example` file for those users who wish to modify their ROS configurations. They can copy this template to a file called `.env` and ros-backend will start with these configs set.

ROS-20 Add .env.example file

---

ros/lib/models.py

PR fixes below bug - 
```
[2021-03-09 10:18:37,018] ERROR in app: Exception on /api/ros/v0/systems [GET]
Traceback (most recent call last):
File "/opt/app-root/lib64/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/app-root/lib64/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/app-root/lib64/python3.8/site-packages/flask_restful/__init__.py", line 468, in wrapper
resp = resource(*args, **kwargs)
File "/opt/app-root/lib64/python3.8/site-packages/flask/views.py", line 89, in view
return self.dispatch_request(*args, **kwargs)
File "/opt/app-root/lib64/python3.8/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
resp …
```

Fix KeyError for performance_score

---

ros/api/v0/hosts.py
ros/openapi/openapi.json

Currently, it works fine for API. For example if we hit: `curl -v -H "Content-Type: application/json"  -H "x-rh-identity: ${b64_identity}" localhost:8080/api/ros/v0/systems?display_name=ap-172-31-11-67.ap-south-1.compute.internal | python -m json.tool`

RHIROS-81 Implement basic filtering for systems

---

ros/api/v0/hosts.py
ros/lib/models.py

Added response fields as per the mockup here: https://marvelapp.com/prototype/9408d9j/screen/74816603.
EDIT:

RHIROS-85 Modify fields in Hosts and Details API responses

---

README.md
scripts/README.md
scripts/docker-compose.yml

Running `# docker-compose up insights-inventory-web db-ros insights-engine` may give the below warning but it can be ignored. 
`insights-engine_1         | KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: platform.inventory.events: Broker: Unknown topic or partition"}`
This PR also solve the issue of creating required topics at the time of initialization.

Added insights-engine in dev environment

---

ros/api/v0/hosts.py
ros/lib/models.py

To handle the following exceptions:
```
Traceback (most recent call last):
File "/opt/app-root/lib64/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/app-root/lib64/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/app-root/lib64/python3.8/site-packages/flask_restful/__init__.py", line 468, in wrapper
resp = resource(*args, **kwargs)
File "/opt/app-root/lib64/python3.8/site-packages/flask/views.py", line 89, in view
return self.dispatch_request(*args, **kwargs)
File "/opt/app-root/lib64/python3.8/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
resp = meth(*args, **kwargs)
File …
```

RHIROS-111 Add exception to fetch model level attributes

---

ros/api/routes.py
ros/api/v0/hosts.py
ros/openapi/openapi.json

API output looks like below - 
```
{
"meta": {
"count": 3,
"limit": 10,
"offset": 0
},
"links": {
"first": "/api/ros/v0/systems/02c4bc40-e507-4b35-a321-732bfe74ba91/history?limit=10&offset=0",
"last": "/api/ros/v0/systems/02c4bc40-e507-4b35-a321-732bfe74ba91/history?limit=10&offset=0",
"next": null,
"previous": null
},
"data": {
"inventory_id": "02c4bc40-e507-4b35-a321-732bfe74ba91",
"performance_history": [
{
"cpu_score": 1,
"memory_score": 3,
"io_score": 1,
"report_date": "2021-05-18"
},
{
"cpu_score": 1,
"memory_score": 3,
"io_score": 1,
"report_date": "2021-05-17"
},
{
"cpu_score": 5,
"memory_score": 3,
"io_score": 5,
"report_date": "2021-05-16"
}
]
}
}
```

API to list historical performance data

---

ros/processor/inventory_events_consumer.py

This commit only enhances the existing log to trace the system and account that have triggered  the exception.
In case of an Exception:
1) If no platform_metadata key (not usually the case, but will be covered in the exception), you can see this output:
```
2021-08-09 21:55:41,102 - ERROR  - run - An error occurred during message processing: KeyError('platform_metadata') in the system 80222848-6007-4753-b91e-2659fa501f8d created from account: 0000001 - PROCESSING Create/Update EVENT
10:34
```
2) If `platform_metadata: None`, you can see:
```
2021-08-09 22:34:04,128 - ERROR  - run - An error occurred during message processing: TypeError("argument of type 'NoneType' is not iterable") in the system a694e7af-743b-45ab-8399-d69e1f98a44d created from account: 0000001 - PROCESSING Create/Update …
```

RHIROS #239 - Add log to trace system during exception

---

cdappconfig.json

Currently, there's no JIRA associated with this PR as it is based on the security alarm raised because of the password present in this file. Although, it is a dummy password, it would be wise to remove it from the file. Secondly, according to https://consoledot.pages.redhat.com/docs/dev/getting-started/migration/config.html#_cdappconfig, this file is generated by clowder. So, not sure if we do want to create it explicitly in our repo.
Based on further discussions, will create a corresponding JIRA as required.

Remove DB section from cdappconfig

---

ros/openapi/openapi.json

Changes:
1. Removed servers object from openapi.json file
Reasons:
1. Getting auto-magically generated; checked on ci.foo and qa.foo via local setup
Issue:
The template string for the servers object was appearing as the default value on the drop-down for Servers:
Hence, the test calls were failing.

RHIROS-357 | REMOVE - OpenAPI servers drop-down has template string

---

Makefile

currently if we run the `make insights-upload-data` command it is failing due to file name error as we recently updated the sample files for uploading data. This PR fixes the file name for same.

Refs #RHIROS 367 - fixed file name in the makefile for uploading data

---

ros/processor/inventory_events_consumer.py
ros/processor/process_archive.py
tests/test_inventory_events_consumer.py

Now the `profile` object in process_archive will contain new metrics with their respective values except `disk.dev.total` and `kernel.all` type metrics which will store its value as an object. This is because we're not processing or using these metrics anywhere in our ros-backend. We're just storing in ros db as performance_record in `performance_profile` table.
Refer the below profile object.
`{
"hinv.ncpu": 8.0,
"total_cpus": 1,
"mem.physmem": 32617072.0,
"instance_type": "t2.micro",
"disk.dev.total": {
"nvme0n1": {
"val": 7.22,
"units": "count / sec"
}
},
"mem.util.available": 27455175.254,
"kernel.all.cpu.idle": 7.55,
"kernel.all.pressure.io.full.avg": {
"1 minute": {
"val": 0.006,
"units": "none"
},
"5 minute": {
"val": 0.004,
"units": "none"
},
"10 second": {
"val": 0.012,
"units": …

RHIROS-401 Update archive processor to store new metrics

---

seed.d/rules.json

Per RHIROS-379, enhance messages to show the details on the issues identified by the new rules for GA, and the list of suggested instances.
This PR introduces two new variables: system.summary and system.candidate_instance_types.
Please note this PR is essentially pseudocode. I have no idea what the actual names of the variables coming from the Advisor rule engine are but it's easier for me to communicate in code than in Google Docs %)

RHIROS-404 - Enhance messages for new rules

---

ros/processor/inventory_events_consumer.py
tests/fixtures/db_fixtures.py
tests/test_inventory_events_consumer.py

1. Added conditions on for platform_metadata on update/create handler function
2. Converted db field parameters for get or create system handler to kwargs
3. Added logic for differentiation of log messages between Create and Update
4. Removed performance profile creation and utilization generator methods
1. The processor should be able to handle `updated` msgs
2. Can be easily modified in case msg['type'] = created
3. Unleash the power of precise logs!
4. Please refer https://github.com/RedHatInsights/ros-backend/pull/138
An attempt to avoid merge conflicts
- IMO we can merge this one post https://github.com/RedHatInsights/ros-backend/pull/138

RHIROS-190 | MOD - System changes on Inventory don't reflect on ROS

---

tests/test_archive_processor.py

Changes:
1. Added test file or archive processor
Reasons:
1. Added test to compare expected and generated performance record data
Additional:
Related to https://github.com/RedHatInsights/ros-backend/pull/137

RHIROS-401 | Added unittest

---

Makefile
ros/api/v0/hosts.py
ros/lib/utils.py
ros/openapi/openapi.json

1. HostsApi modified marshall fields and added io dict sorting, max_io
2. HostDetailsApi modified marshall fields and added io dict sorting, max_io
to keep it consistent with HostsApi
3. HostHistoryApi io values are now dict and sorted on values
4. max_io added to build_sort_expression for enabling ASC and DESC sorting
5. Added util function for sorting io_dict
6. Modified Make file for easier testing, can be reverted if deemed not necessary
`/api/ros/v0/systems?order_by=max_io&order_how=DESC`
```
"data": [
{
"fqdn": "rhel8-test.hyrdvbbl3ugefmkdahnvv2bx1h.rx.internal.cloudapp.net",
"display_name": "rhel8-test.hyrdvbbl3ugefmkdahnvv2bx1h.rx.internal.cloudapp.net",
"inventory_id": "f73715ea-00b6-4a02-a4aa-528584b04dfd",
"account": "0000001",
"number_of_suggestions": 0,
"state": "Optimized", …
```

RHIROS-393 | io Utilization as dict and max_io

---

ros/api/v1/hosts.py
ros/openapi/openapi.json

Output for `/api/ros/v0/is_configured`:
```python
{
"success": true,
"code": "SYSTEMSEXIST",
"count": 30,
"systems_stats": {
"waiting_for_data": 1,
"with_suggestions": 16
}
}
```

RHIROS #435 - Update is_configured api to serve system stats

---

ros/processor/main.py

As metrics port value set as string in template, currently it is failing while restarting http server. 
To fix this, converting metrics port value to integer before passing as argument.

Refs RHIROS 133 - fix type error for metrics port

---

ros/processor/insights_engine_result_consumer.py
ros/processor/process_archive.py
sample-files/insights-engine-result-idle.json
sample-files/insights-engine-result-no-pcp.json
sample-files/insights-engine-result-optimized.json
sample-files/insights-engine-result-undersized.json
tests/test_archive_processor.py
tests/test_insights_engine_result_consumer.py

Getting `region` value from rule hit won't work for optimized state. Not able to get `region` for NO_PCP_DATA also. Hence, using performance_record to get the `region` value, storing it in `systems` table and discarding it from `performance_record.` Also discarding `instance_type` from performance_record as we already have instance_type column in systems table.
Added tests for no-pcp, undersized and optimized states

RHIROS-449 Get region from performance_record

---

ros/openapi/openapi.json

Changes:
1. cpu and memory types on SystemDetails schema and SystemItem schema
Reasons:
1. Value types are referred by server on deserialization

RHIROS-460 | Util value types on openapi.json

---

saas-templates/_imagestreams.yaml
saas-templates/ros-backend.yaml
saas-templates/ros-db.yaml
saas-templates/ros-processor.yaml

1. Created saas_templates folder at root level and added the deployment templates
https://mailman-int.corp.redhat.com/archives/insights-platform/2022-January/msg00011.html

RHIROS-465 | Move deployment templates to github repository

---

ros/api/v1/hosts.py
ros/lib/utils.py
ros/openapi/openapi.json
ros/processor/insights_engine_result_consumer.py

Changes are based on the assumption that IOPS values are actuals from rules

RHISOS 470 | IOPS Values from Rules are actuals

---

ros/openapi/openapi.json

1. Updated `orderByParam` from `io` to `max_io` on openapi file
1. `io` is now longer a sortable parameter

RHIROS-469 | orderByParam is now max_io instead of io, systems endpoint

---

ros/openapi/openapi.json

Changes:
1. Updated orderByParam from io to max_io
Reasons:
1. io is now longer a sortable parameter

RHIROS-469 | (Cherry-picked) orderByParam is now max_io instead of io, systems endpoint

---

clowdapp.yaml

This is to identify the deployments are from clowder.

RHIROS 476 - Add service suffix for deployment names

---

ros/processor/insights_engine_result_consumer.py
tests/test_insights_engine_result_consumer.py

1. no-pcp state stores -1 for util values and `number_of_suggestions`
2. unittests updated
1. Change helps with the sorting functionality on ROS home page 
2. `0` seems like an inappropriate util value for a system that is Waiting for data

RHIROS-474 | -1 util values for "Waiting for Data" state

---

clowdapp.yaml

This is w.r.t to  rollback on prod.
Issue: Traffic on prod is currently being routed to non-existent clowder pods(these don't spin up for some reason)

Renaming Clowder deployments

---

ros/lib/cw_logging.py

Fix for the following error on Openshift pods:
```
File "/opt/app-root/src/ros/lib/cw_logging.py", line 46, in commence_cw_log_streaming
watchtower_handler = watchtower.CloudWatchLogHandler(
File "/opt/app-root/lib64/python3.8/site-packages/watchtower/__init__.py", line 193, in __init__
super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'boto3_session'
```
Docs do suggest to use `boto_session` :shrug: 
References:
1. https://github.com/RedHatInsights/vmaas/blob/master/vmaas/common/logging_utils.py#L64
2. https://stackoverflow.com/questions/70954418/django-logging-with-watchtower-got-an-unexpected-keyword-argument-in-handler
Related to #163

RHIROS-391 | Kibana Logging - Renamed client/session keyword for watchtower.CloudWatchLogHandler

---

ros/lib/config.py
ros/lib/cw_logging.py

1. Replaced Session with boto3.client, service name for the same needs to be 'logs'
2. watchtower handler now being added to root logger
3. watchtower handler has its own formatter
* Independently tested with custom flask app logging and private aws account
Related to #190 #189

RHIROS-391 | Cloudwatch Logging - watchtower/boto3 errors

---

Pipfile
Pipfile.lock

Changes:
1. insights-core source(PyPi)
2. markupsafe explicit downgrade to 2.0.1
Reasons:
1. git has over 70 dependencies, these end up in the final app image
2. markupsafe's latest version has a bug, [here](https://github.com/aws/aws-sam-cli/issues/3661)

 RHIROS-471 | Pipfile Updates

---

migrations/versions/015d7d1fea52_update_performance_profile_table.py
migrations/versions/26a16593ec96_remove_columns_from_systems.py
migrations/versions/3d3a1981593c_populate_fields_from_systems_to_.py
migrations/versions/457844090fad_set_keys_on_performance_profile_history.py
migrations/versions/77fdc857c94f_alter_pk_on_performance_profile.py
migrations/versions/8c6f4554d24d_create_performance_profile_history.py
migrations/versions/ccf59577aca2_keep_last_reported_in_perf_profile.py
ros/api/v1/call_to_action.py
ros/api/v1/hosts.py
ros/api/v1/recommendations.py
ros/lib/config.py
ros/lib/models.py
ros/lib/utils.py
ros/processor/garbage_collector.py
ros/processor/insights_engine_result_consumer.py
ros/processor/inventory_events_consumer.py
tests/fixtures/db_fixtures.py
tests/helpers/db_helper.py
tests/test_api_endpoints.py
tests/test_garbage_collector.py
tests/test_insights_engine_result_consumer.py

RHIROS-573,574,575,601,576,577 - Historical data support

---

ros/processor/insights_engine_result_consumer.py
ros/processor/inventory_events_consumer.py

RHIROS-644 - modify log messages from processors

---

Makefile
clowdapp.yaml
ros/lib/utils.py
ros/processor/main.py
tests/test_utils.py

In this PR we are giving each processor a name(processor_name) and adding its reference to PROCESSOR_INSTANCES array. Also we are giving names to each thread where [thread_name](https://github.com/RedHatInsights/ros-backend/pull/220/files#diff-6f48879fb5d9b6c7702c5db83686f993f3fc502e881d30167dd873207967c756L28) is equal to [processor_name](https://github.com/RedHatInsights/ros-backend/pull/220/files#diff-6f48879fb5d9b6c7702c5db83686f993f3fc502e881d30167dd873207967c756R14).
Idea is to simple get the names of all the [running thread](https://github.com/RedHatInsights/ros-backend/pull/220/files#diff-73b796983793ca68d788f97a84b00ef19df5157d5fee7ee854c47ed1133d45f1R160) and check if all PROCESSOR_INSTANCES name is present in list of running thread. if any of the thread is missing/dead we send …

RHIROS-689 Added monitoring process for Openshift props

---

clowdapp.yaml

added ros api path in clowdapp.yaml.
As we had not set the api path in clowdapp.yaml, in EE it was using app name and due to this the frontend was not working in the EE. This PR fixes the issue. 
References:
https://ansible.slack.com/archives/C023VGW21NU/p1656075925640389?thread_ts=1655715454.841739&cid=C023VGW21NU
https://coreos.slack.com/archives/C022YV4E0NA/p1656071317819399

added ros api path in clowdapp.yaml

---

Pipfile
Pipfile.lock
clowdapp.yaml
ros/api/main.py
ros/api/v1/call_to_action.py
ros/lib/app.py
ros/lib/config.py
scripts/docker-compose.yml

We are getting many hits on call_to_action API, reason - call_to_action API gets called from console dashboard so for every user coming to consoledot will hit call_to_action API though he/she is not a ROS user. To reduce DB connections/queries adding redis to cache the call_to_action API with TTL of 5 mins.
**Note - Do not merge this PR before merging app-interface MR linked in JIRA ticket.**

RHIROS-731 Added API caching for ROS

---

clowdapp.yaml
ros/lib/app.py
ros/lib/config.py

Seems like API caching has not solved the QueuePool size limit issue. We will need to increase the `SQLALCHEMY_POOL_SIZE`. 
I have checked other services like [vulnerability-engine](https://github.com/RedHatInsights/vulnerability-engine/blob/d31b67a7223ff69ee3c4220e79304268f2363c62/deploy/clowdapp.yaml#L914), [payload-tracker](https://github.com/RedHatInsights/payload-tracker/blob/827f66ce3c2810abcfc3acfa9cee1021141827ad/deploy/deploy.yml#L259) etc they are having higher pool size.

Refs #RHIROS-731 - Increase SQLAlchemy DB pool size

---

Dockerfile

1. `Dockerfile` changes
1. An official and minimal image is preferable
2. Helps with faster mitigation of security concerns
A sample image has been pushed at `quay.io/sdutta/ros_base_ubi8_api:latest`
Awaiting security analysis on the same, currently queued.
Here's a version of the source code with the updated Dockerfile, along with a docker-compose file
for the ease of testing.
[ros_base_ubi8.zip](https://github.com/RedHatInsights/ros-backend/files/8832276/ros_base_ubi8.zip)
The idea is to spin up an API container successfully, then
- Check if the urls are responsive
- Exec into the container and check if any insecure packages are available in the same
Steps:
1. Unzip the file
2. `cd ros_base_ubi8/`
3. `docker-compose up --build`
Container should be ready now.
**Note**: 75% of the …

RHIROS-471 | ROS Base Image update - ubi8/ubi-minimal

---

ros/lib/config.py

Fixes https://issues.redhat.com/browse/RHIROS-811
This makes use of the app-common-python function here: https://github.com/RedHatInsights/app-common-python/blob/master/app_common_python/__init__.py#L16
This function store the .pem in a tmpfile and returns the file path.

Store kafka cacert in tmpfile

---

clowdapp.yaml

----
- Updating references from the old 3scale dev deployment `apicast.3scale-dev.svc.cluster.local` to the new 3scale dev deployment `gateway.3scale-dev.svc.cluster.local`
- The reason for this change is the Infrastructure Team has stood up a new 3scale (Gateway) Deployment to support service serving certificates. Currently, both the old and new deployments are running in parallel so we can aid workstreams in the change over.

Update References to 3Scale Dev Deployment

---

ros/processor/event_producer.py

Refer sample kafka messages:
- https://github.com/RedHatInsights/ros-backend/blob/main/tests/data_files/insights-engine-result-idle.json#L36
- https://github.com/RedHatInsights/ros-backend/blob/main/tests/data_files/events-message.json#L1126
Key should be `account` instead of `account_id`.

Fixes #RHIROS-837 - fix account info in events

---

ros/api/v1/hosts.py
ros/openapi/openapi.json
tests/test_api_endpoints.py

Removed hardcoded os versions.
Now, we're showing os versions in the os filter that are registered with a user account.
- If all child versions are selected then their parent version will be selected automatically.
- If a parent version is selected then all its child versions will be selected automatically.
API docs
UI

RHIROS-892 update os filtering logic

---

ros/api/v1/hosts.py
tests/test_api_endpoints.py

1. Added model field for anonymous table
2. Added RHEL 7 filter for non_psi_count
3. Added unit-test
'is' operator does not work well sqlalchemy equality comparisons. 
Hence, a #noqa comment as been used so that flake8 doesn't complain
Reference, [here](https://stackoverflow.com/questions/18998010/flake8-complains-on-boolean-comparison-in-filter-clause)

RHIROS-777 | Exclusion filter for RHEL 7 systems - non-psi-count

---

ros/api/common/utils.py
ros/api/v1/recommendation_ratings.py
ros/openapi/openapi.json
tests/test_api_endpoints.py

With this commit, server will return proper error code & message instead of 500 server error on submitting invalid value against rating via /recommendation_ratings POST API request.
With latest changes, additionally handled below scenarios:
- when user sends invalid JSON or incorrect JSON format 
- when user sends invalid inventory_id

Fixes #RHIROS-786 - handle exception on invalid value for rating

---

ros/api/v1/hosts.py

The current executive report join query does not look into `rh_accounts`, technically.
The `and` in the filter for join doesn't really work and neither does complain :shrug: 
SQL statement from is_configured,
```
SELECT performance_profile.system_id
FROM performance_profile
WHERE performance_profile.system_id IN (SELECT systems.id AS systems_id
FROM systems
WHERE systems.tenant_id IN (SELECT rh_accounts.id
FROM rh_accounts
WHERE rh_accounts.org_id = %(org_id_1)s))
```
SQL statement from executive_report,
```
SELECT systems.id, systems.state, systems.instance_type, systems.cpu_states, systems.io_states, systems.memory_states, …
```

RHIROS-934 Bad filter on join - Executive report v2

---

ros/api/v1/hosts.py
ros/lib/utils.py

1. Added RHEL 7 filter for psi-enabled-count

RHIROS-928| Exclusion filter for RHEL 7 systems - psi-enabled-count

---

ros/api/v1/hosts.py

As of now, UI is sending numeric values for OS versions like 8.4

Ref-RHIROS-892 remove FIXME from os filtering logic

---

Pipfile
Pipfile.lock

Minimal locking of pytest with suggested version on dependabot alert.
Currently, a minimum version locking is not present in Pipfile  for the package.
Please check JIRA card for more details.

RHIROS-922 Bump pytest version

---

pr_check.sh

pr_check job by default deploy all the components present in app-interface. Setting COMPONENTS variable explicitly specify which component to deploy. 
**PR not worth of creating the issue in JIRA**
PR check job is failing as we have added new resource template for ros-ocp in app-interface
https://ci.int.devshift.net/job/RedHatInsights-ros-backend-pr-check/446/console

Add COMPONENTS env variable in pr_check

---

ros/api/v1/hosts.py

Use iso format for `report_date`. 

RHIROS-623 show iso format date in api endpoints

---

scripts/docker-compose.yml

Unable to hit inventory API in local setup. 
```
curl http://localhost:8001/api/inventory/v1/hosts
curl: (7) Failed to connect to localhost port 8001 after 0 ms: Connection refused 
```

Fixes #RHIROS-1046 - Added env variable in docker-compose

---

ros/lib/utils.py
ros/processor/inventory_events_consumer.py

Scenario:
When ROS is enabled for an existing System on Managed Inventory, the event type is 'updated'.
Changes:
1. Checking for system_metadata along with msg type
2. Assert valid update on inventory consumer with system_metadata
Tested with local inventory PATCH:
```
inventory-patch-upload:
curl -X PATCH "[http://localhost:8001/api/inventory/v1/hosts/{1ca44105-16a0-45a7-b33a-d56d781a0c7b}](http://localhost:8001/api/inventory/v1/hosts/%7B1ca44105-16a0-45a7-b33a-d56d781a0c7b%7D)" \
-H "x-rh-identity: ${b64_identity}" \
-H "Content-Type: application/json" \
-H "Accept: application/json" \
-d '{"display_name": "host1.mydomain.com"}'
```
Update event …

RHIROS-1122  Create for existing system on Managed Inventory

---

scripts/docker-compose.yml

We need to explicitly start redis or it should be added as dependency for Puptoo. The local setup stopped working as Puptoo depends on redis however it was not getting started as dependency,
~~~
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/src/puptoo/app.py", line 133, in main
handle_retries(redis, extra["request_id"])
File "/usr/local/lib/python3.8/site-packages/src/puptoo/app.py", line 81, in handle_retries
count = redis.get(request_id)
File "/usr/local/lib/python3.8/site-packages/redis/commands/core.py", line 1801, in get
return self.execute_command("GET", name)
File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1266, in execute_command
conn = self.connection or …

Add redis as required dependency for Puptoo

---

ros/lib/config.py

Forcing redis to run over SSL when password is present as in app-interface. 
Updating all of the various apps that will be running in environments where SSL is enforced we need to toggle `redis://` -> `rediss://` when the password is present.

Run redis over ssl when password is present

---

ros/lib/utils.py
tests/data_files/events-message.json
tests/data_files/insights-engine-result-idle.json
tests/data_files/insights-engine-result-no-pcp.json
tests/data_files/insights-engine-result-optimized.json
tests/data_files/insights-engine-result-under-pressure.json
tests/data_files/insights-engine-result-undersized.json

Update `is_ros` field from `string` to `boolean` as Puptoo is now sending `boolean` value.
Ref - [ESSNTL-4611](https://issues.redhat.com/browse/ESSNTL-4611)

update is_ros flag

---

migrations/versions/1051e0d7e62e_update_default_value_for_group_column.py
tests/fixtures/db_fixtures.py

Ref-RHIROS-1156 handle default value for group

Ref-RHIROS-1156 handle default value for group

---

ros/lib/config.py

This is a requirement for some environments.
- Added a check for the clowder configured RDS CA
- Tack the SSL mode onto the DB URI if it exists
I don't have a JIRA for this one. Just noticed this as an issue in one of our environments that requires SSL so I took the "patches welcome" approach
Some environments require SSL connectivity to the RDS databases. Clowder can provide this cert so we should look for it if it exists
This is just a suggestion for how to do this that should get SSL support into the code. If there are other patterns that the ROS team would like to use, that's fine by me.

feat: Add ability to connect to DB with ssl

---

ros/api/common/add_group_filter.py
ros/api/common/utils.py
ros/api/v1/hosts.py
ros/api/v1/recommendation_ratings.py
ros/api/v1/recommendations.py
ros/lib/rbac_interface.py
tests/conftest.py
tests/data_files/mock_rbac_returns_emtpy_group.json
tests/data_files/mock_rbac_returns_groups_including_example_group.json
tests/data_files/mock_rbac_returns_no_groups.json
tests/fixtures/db_fixtures.py
tests/fixtures/db_fixtures_for_inventory_groups.py
tests/test_api_endpoints.py

The RBAC now returns groups to which user has access to. The System and dependent objects should be gated as per the group details.

Fixes #RHIROS-1266 - Add groups support through RBAC

---

ros/api/common/add_group_filter.py

Refs #RHIROS-1266 - fix condition to use group query

---

ros/lib/rbac_interface.py
tests/data_files/mock_rbac_returns_array_of_groups.json
tests/data_files/mock_rbac_returns_emtpy_group.json
tests/data_files/mock_rbac_returns_groups_including_example_group.json
tests/data_files/mock_rbac_returns_multiple_read_permissions.json
tests/data_files/mock_rbac_returns_multiple_types_of_read_permissions.json
tests/data_files/mock_rbac_returns_no_groups.json
tests/fixtures/db_fixtures_for_inventory_groups.py
tests/test_api_endpoints.py

The RBAC returns multiple read permissions in different formats, this change handles that.

Fixes #RHIROS-1312 - update RBAC filters

---

ansible-playbooks/ros_install_and_set_up.yml

The pmlogger is using pmsocks which is needed when monitoring the systems protected by firewall. As this is local configuration this is not required, so removing this unnecessary option.

Don't use pmsocks in pcp config

---

build_deploy.sh

This PR updates the 'Security-Compliance Tag' Naming Convention within the 'build_deploy.sh' to make it easier to identify the Git Commit the image is based on.
Example:
OLD: `sc-20230916`
NEW: `sc-20230916-83f605f`

Update build deploy scripts.

---

ros/api/common/add_group_filter.py
ros/lib/rbac_interface.py
tests/data_files/mock_rbac_returns_inventory_hosts_read_without_groups.json
tests/data_files/mock_rbac_returns_inventory_hosts_star_without_groups.json
tests/data_files/mock_rbac_returns_inventory_star_read_without_groups.json
tests/data_files/mock_rbac_returns_inventory_star_star_without_groups.json
tests/test_api_endpoints.py

When user has 'inventory:hosts:*' or 'inventory:hosts:read' or 'inventory:*:*' or 'inventory:*:read' permissions
and resource definition does not have any groups it means user can see all the systems on ROS

Refs #RHIROS-1312 - handle inventory and hosts admin

---

poetry.lock
pyproject.toml

`AttributeError: 'RedisCache' object has no attribute '_client'`
The above is caused by `flask_caching` [v1.11.1](https://github.com/pallets-eco/flask-caching/pull/372) and is fixed in v2.0.0.
To upgrade it to the latest one we need to pin `flask` <v3.0.0 as its latest version (2.0.2) depends on Flask (<3). 
And in turn, we would need to pin `werkzeug` <v3.0.0

Pin flask_caching to <=2.0.2

---

.tekton/ros-backend-pull-request.yaml
.tekton/ros-backend-push.yaml

The ROS requires rpm packages to start itself. The HERMETIC builds does not allow pulling anything extra apart from what is mentioned in poetry.lock file. There is ticket https://issues.redhat.com/browse/RHTAP-252 which would allow creating preinstalled rpm env for HERMETIC builds until then we should build it in non HERMETIC mode.

Don't do HERMETIC builds

---

ros/lib/utils.py
ros/processor/inventory_events_consumer.py

The platform_metadata use to be empty if there is nothing in it, however now when its empty it at least has "bs64_identity". This breaks ROS use cases as we use to depend on "platform_metadata" being None!

Fixes #RHINENG-5908 - handle updated platform_metadata dict

---

.github/workflows/security-scanning.yml
Dockerfile

Enabling the `Platform Security GitHub Workflow` - This workflow provides Red Hat ConsoleDot Teams with a way to scan the containers they create in a convenient, automated, and reliable manner within their GitHub repository. The Platform Security Github Workflow lets teams get security feedback as they open Pull Requests.
Additionally, the `FROM` statement in the `Dockerfile` has been changes to `registry.access.redhat.com` to ensure that the security scanner and pull the Base Image without needing to authenticate with the RH Registry. 
REF: https://github.com/RedHatInsights/platform-security-gh-workflow

Enable Platform-Security GitHub Workflow

---

.github/workflows/build_with_latest_direct_deps.yml
pyproject.toml

The PR is for fixing the below error.
```
Installing the current project: ros-backend (2.4.0) 
Warning: The current project could not be installed: No file/folder found for package ros-backend 
If you do not want to install the current project use --no-root. 
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file. 
If you did intend to install the current project, you may need to set `packages` in your pyproject.toml file.
```

fix pyproject toml file

---

ros/lib/config.py
ros/processor/main.py
ros/processor/suggestions_engine.py
tests/test_suggestions_engine.py

Listens to the Inventory topic (`platform.inventory.events`) and downloads archives based on `is_ros_v2` and `is_pcp_raw_data_collected` flags.

RHINENG-13972 download and extract archive

---

README.md

update readme to remove stale information

---

ros/lib/pcp_extract_config
ros/processor/suggestions_engine.py
tests/test_suggestions_engine.py

Run `pmlogextract` on the extracted `.index` file, followed by `pmlogsummary` on the resulting output file.

RHINENG-13973 execute pcp commands

---

.github/workflows/build.yml
.github/workflows/build_with_latest_direct_deps.yml
.github/workflows/build_with_latest_indirect_deps.yml
.github/workflows/codeql.yml

`action/cache` versions v1 and v2 are deprecating. We need to upgrade it to v4.
References: [https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/)

RHINENG-15954 upgrade action/cache to v4
