- local-ros-backend.js
This route can be added in the frontend's local-frontend.js file as and when required for development purposes only.
> RHIROS-45 Create local-ros-backend.js for routes

- ros/api/common/pagination.py
- ros/resources/v0/hosts.py
Refer - https://platform-docs.cloud.paas.psi.redhat.com/rest/pagination.html
> implement pagination for systems list

- ros/app.py
- ros/config.py
- ros/processors/inventory_events_consumer.py
- ros/processors/inventory_events_listener.py
- ros/processors/report_processor.py
> Fixes #41 - listen to inventory's events

- ros/models.py
- ros/resources/v0/hosts.py
Computing scores `1-5` in the model.
> ROS-26 Compute scores in API

- ros/api/v0/hosts.py
- ros/lib/utils.py
In collaboration with @semtexzv this PR enhances and replaces [#34](https://github.com/RedHatInsights/ros-backend/pull/34)
> Fix API calls of ROS backend. 

- ros/api/v0/hosts.py
With this commit, it will correct the HOST API response.
Introduced by [PR-20](https://github.com/RedHatInsights/ros-backend/pull/20).
> correct host API's response

- ros/processor/insights_engine_result_consumer.py
EDIT - with this change, my [concern](https://github.com/RedHatInsights/ros-backend/pull/55#discussion_r610543479) on #55 will also get resolved :)
> RHIROS-151 - update state=optimized to system when no rule hits

- ansible-playbooks/ros_install_and_set_up.yml
> RHIROS-170 Add RHEL8 for ARM arch

- ansible-playbooks/ros_install_and_set_up.yml
> RHIROS-171 Ansible tasks to support ROS setup on RHEl7

- ansible-playbooks/ros_install_and_set_up.yml
* Removed rhsm tasks for configuring rhui repos
* Moved debug statements to the top
* Formatting changes
> Removed rhsm tasks from ros-setup playbook

- ansible-playbooks/ros_install_and_set_up.yml
WIP - Adds a few tasks to fetch
> [WIP] RHIROS-254 - Print URL at the end of playbook to find system

- ros/processor/garbage_collector.py
- ros/processor/insights_engine_result_consumer.py
- ros/processor/inventory_events_consumer.py
Output should look like - 
```python
2021-10-14 20:11:06,932 - INFO  - remove_outdated_data - GARBAGE COLLECTOR - Deleting performance profile of the system: 25e1fa44-5b92-4e42-a036-74ebc01e9711 older than 14 days
2021-10-14 20:11:06,938 - INFO  - remove_outdated_data - GARBAGE COLLECTOR - Deleting performance profile of the system: ef457b61-ffb0-410e-aa46-9294127a37ba older than 14 days
2021-10-14 20:11:15,871 - INFO  - process_system_details - PROCESSING Create/Update EVENT - Refreshed system ee06eb42-c70d-4ad2-a68a-97300e62096e (16) belonging to account: 0000001 (1) via report-processor
2021-10-14 20:11:17,766 - INFO  - process_report - PROCESSING ENGINE RESULTS - Marking the state of system with inventory id: ee06eb42-c70d-4ad2-a68a-97300e62096e as Oversized.
2021-10-14 20:11:17,783 - …
```
> RHIROS #356- Enhance logging in processors

- ros/processor/garbage_collector.py
- ros/processor/insights_engine_result_consumer.py
- ros/processor/inventory_events_consumer.py
* RHIROS #356- Enhance logging in processors
* Modified logs with prefixes
* Keep garbage collector same & refine log msgs
(cherry picked from commit afb714191906d4512da3114c0b233c6b38889b5f)
> Update stable with logging change

- ros/processor/inventory_events_consumer.py
- tests/test_inventory_events_consumer.py
With this commit, it will show correct values for host id and account.
Message object is different for create/updated and delete event.
It seems that these keys were introduced quite sometime ago but issue never caught before.
> Refs RHIROS-385 - fixes host keyerror

- Pipfile.lock
as new version of insights-core pkg is available.
+ @r14chandra into loop as this is relevant to RHIROS-401.
> Refs #RHIROS-401 - add Pipfile.lock

- ros/api/v0/hosts.py
- ros/openapi/openapi.json
- ros/processor/insights_engine_result_consumer.py
My bad! I didn't notice before merging PR https://github.com/RedHatInsights/ros-backend/pull/142
> Refs RHIROS#403 - fix string format

- ros/lib/utils.py
- ros/processor/insights_engine_result_consumer.py
1. Explicit convert of cpu, memory to int
* max_io and io dict value types are pending
* Reference: https://github.com/RedHatInsights/ros-backend/pull/150#issuecomment-996115794
> RHIROS-402 | Correction on util data types

- ros/openapi/openapi.json
Changes:
1. Ordered util values as they appear on API response
2. Modified limit param description text
3. Added inventory_id on PerformanceHistory schema
4. Updated host_id to inventory_id in SuggestionsList schema
5. Removed un-available state filter parameters
Reasons:
* Consistency
> RHIROS-475 | OpenAPI docs misc. ROS v1

- ros/openapi/openapi.json
Ordered util values as they appear on API response
Modified limit param description text
Added inventory_id on PerformanceHistory schema
Updated host_id to inventory_id in SuggestionsList schema
Removed un-available state filter parameters
* Consistency
> RHIROS-475 | (Cherry Pick) OpenAPI docs misc. ROS v1

- pr_check.sh
Ref - https://issues.redhat.com/browse/RHIROS-494
> [RFR] Updating pr_check.sh file

- ansible-playbooks/ros_install_and_set_up.yml
Jira card for reference:
https://issues.redhat.com/browse/RHIROS-496
> Replacing returned url in playbook.

- clowdapp.yaml
> Update clowdapp name

- clowdapp.yaml
> Updating backend deployment name for clowder

- Pipfile
- Pipfile.lock
- ros/api/main.py
- ros/lib/config.py
- ros/lib/cw_logging.py
- ros/processor/main.py
- tests/test_api_endpoints.py
1. Added cw_logging.py module
2. Introduced relevant environment variables vars on config.py
3. Added CloudWatch streaming function calls in processor and api
4. Added dependencies on Pipfile and regenerated Pipfile.lock
5. Cleaned up a pesky print statement from test_system_detail
1. Houses streaming handler function
2. Necessary for authenticating with relevant AWS account
3. Invokes the handler function
4. Mentioning and locking dependencies
* Tests have not been added since 95% of the changes is meant to function on Openshift
- [Documentation](https://consoledot.pages.redhat.com/docs/dev/platform-documentation/tools/logging.html)
- [Sample code](https://github.com/RedHatInsights/vmaas/blob/master/vmaas/common/logging_utils.py)
> RHIROS-391 | Log streaming to CloudWatch -> Kibana Dashboard

- ros/lib/cw_logging.py
> RHIROS-391 | CW Logging - Re-introduced session object

- ros/api/routes.py
- ros/api/v1/call_to_action.py
Payload for no. of systems greater than zero
Payload for no. of systems equals to zero
> RHIROS-512  ROS CTA

- ros/api/v1/hosts.py
- ros/lib/models.py
- tests/test_api_endpoints.py
Changes:
1. Added conditional init for 'os' in system detail and systems api
2. Added relevant test for system detail endpoint
> RHIROS-565 | Handle records with no operating_system data

- ros/api/routes.py
- ros/api/v1/hosts.py
Changes:
1. Modification in url
> RHIROS-596 | ExecutiveReportAPI with Dummy response

- ros/api/routes.py
- ros/lib/config.py
- saas-templates/ros-backend.yaml
- saas-templates/ros-processor.yaml
1. Set CW_ENABLED to str on respective saas-templates
2. Addressed a flake8 warning in routes.py
> Bugfix | ROS Prod Deployment 30-03-2022

- saas-templates/ros-backend.yaml
- saas-templates/ros-processor.yaml
Reference: https://gitlab.cee.redhat.com/insights-platform/saas-templates/-/blob/master/templates/advisor/insights-advisor-api.yaml#L109
> Initialization of AWS env vars for logging | Attempt 2

- ros/api/v1/hosts.py
- ros/openapi/openapi.json
Fixed default ordering to report data instead of name
Jira: https://issues.redhat.com/browse/RHIROS-617
https://drive.google.com/file/d/1WT3QS8qr8olwu_lFTxKLz0iNGoINcVqG/view?usp=sharing
> RHIROS-617 fixed default ordering to report date instead of name

- ros/api/routes.py
- ros/api/v1/recommendations.py
- ros/openapi/openapi.json
- seed.d/rules.json
Response modification for suggestions endpoint. Added three more fields: `current_instance`, `detected_issues`, `suggested_instances` 
**/suggestions endpoint response:**
> RHIROS-608 Update UI for showing suggestions on ROS details page

- clowdapp.yaml
[Urgent] Need this change to override env vars related to Garbage collector processor for testing and for future use.
> Refs RHIROS-576 - add env params in clowdapp.yaml

- clowdapp.yaml
- run_org_id_populator.yaml
Merge this after #226 
NOTE: Needs DEV-PROD team to run this job on stage and prod.
> RHIROS-652 add org-id-populator job

- ros/processor/insights_engine_result_consumer.py
Note that - Advisor rules side change is fixed but not yet available.
Also, I am waiting for inputs on issue [comment](https://issues.redhat.com/browse/CEECBA-6393?focusedCommentId=20622461&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-20622461).
> RHIROS-739 - set cloud_provider info to host in engine processor

- ros/api/v1/hosts.py
Note that from local setup I can see current logic uses 14 SQL count queries and 3 SQL select queries.
With this commit, now it uses 7 count queries and 1 SQL select query.
Any suggestions on how we can make this code more efficient as currently I am iterating on all non optimized systems?
> Fixes #RHIROS-759 - refactor executive_report API for SQL queries

- ros/processor/inventory_events_consumer.py
- tests/test_inventory_events_consumer.py
Changes:
1. Added an assert for cloud provider value for  update events
2. Added unittest
Additional:
- NA
> RHIROS-733 | Cloud provider check for Update events

- clowdapp.yaml
Reference - https://consoledot.pages.redhat.com/clowder/dev/api_reference.html#k8s-api-github-com-redhatinsights-clowder-apis-cloud-redhat-com-v1alpha1-deployment
> Refs #RHIROS-757 - Fix replica param location

- ros/api/v1/hosts.py
- ros/openapi/openapi.json
Changes:
1. Addition of psi_enabled_count in API response
> RHIROS-777 | Add PSI enabled system count in Exec Report response

- ros/api/v1/hosts.py
- ros/openapi/openapi.json
Changes:
1. Updated OS_VERSIONS with RHEL 8.6, 9.0
Additional:
- NA
> RHIROS-701 | Add latest RHEL releases for filtering

- .github/workflows/build.yml
Referred - https://github.com/codecov/codecov-action
> Fixes #RHIROS-833 - upload coverage to codecov in github workflow

- .github/workflows/codeql.yml
This change addresses the SEC-APP-REQ-2 SAST requirement as per ESSv9 assessment and recommendations for ROS
> PLMPGM-620 [SEC-APP-REQ-2] | CodeQL action for Static application security testing (SAST)

- .github/pull_request_template.md
A PR creation template for ROS back-end repo
> RHIROS-840 | Add a Github PR creation template

- ros/api/common/utils.py
- ros/api/v1/hosts.py
- ros/lib/rbac_interface.py
- ros/lib/utils.py
- ros/processor/event_producer.py
- ros/processor/garbage_collector.py
- ros/processor/insights_engine_result_consumer.py
- ros/processor/inventory_events_consumer.py
- ros/processor/process_archive.py
> RHIROS-456 fix inconsistent log format

- ros/lib/config.py
- ros/lib/rbac_interface.py
> Refs #RHINENG-103 - remove REQUESTS_CA_BUNDLE env

- clowdapp.yaml
- ros/processor/garbage_collector.py
- ros/processor/insights_engine_consumer.py
- ros/processor/insights_engine_result_consumer.py
- ros/processor/inventory_events_consumer.py
- ros/processor/main.py
- scripts/docker-compose.yml
- tests/test_insights_engine_result_consumer.py
This PR will help to deploy ROS processors in separate pods. For development environment we will still run the processors in multi-threaded process.
> Fixes #RHIROS-889 - Decouple ROS processors deployment

- ros/api/common/utils.py
- tests/test_api_endpoints.py
> Fixes #RHIROS-400 - fix improper authorization while submitting rating

- ros/processor/insights_engine_consumer.py
- ros/processor/inventory_events_consumer.py
- ros/processor/process_archive.py
> RHIROS-660 improve processor logs

- gunicorn.conf.py
- ros/lib/app.py
> Fixes #RHIROS-953 -  add HTTP security headers in response

- scripts/docker-compose.yml
With latest ingress image archive upload fail in local dev setup. Below is the error observed when try to upload archive. 
```
HTTP/1.1 415 Unsupported Media Type
```
Can we make exception for such small PR and merge it directly without creating Jira ticket. Although PR check for PR title will fail.
> Fix local dev setup

- ros/lib/app.py
- ros/lib/config.py
- ros/lib/rbac_interface.py
**Note that** - I haven't removed env PATH_PREFIX as I want to make sure that there is no other cases where this can be useful. Instead of removing for now just modified the default value same as clowdapp file as this is inconsistent previously.
> Fixes #RHIROS-955 - make openapi file publicly accessible

- ros/lib/utils.py
- ros/processor/insights_engine_consumer.py
- ros/processor/inventory_events_consumer.py
To avoid processing archives that are not from cloud providers.
Merge this PR before - [insights-puptoo-#269](https://github.com/RedHatInsights/insights-puptoo/pull/269)
> RHIROS-1035 add cloud_provider check to avoid processing on-premise archives

- ros/lib/constants.py
- ros/lib/utils.py
- ros/processor/inventory_events_consumer.py
- tests/test_inventory_events_consumer.py
> RHIROS-1112 - process systems on update event without platform_metadata

- .github/workflows/build.yml
> Don't fail the CI if codecov upload fails

- .github/workflows/build_with_latest_direct_deps.yml
- .github/workflows/build_with_latest_indirect_deps.yml
We need github action to keep testing our pr changes for latest available dependencies so as a team we feel comfortable to upgrade to them.
> Actions to test the code for latest indirect and direct deps

- ros/api/v1/recommendations.py
- ros/openapi/openapi.json
> RHIROS-1125 add psi_enabled value to /suggestions endpoint

- scripts/docker-compose.yml
Updated xjoin image to latest to fix local dev setup
to fix local dev setup
> Updated xjoin image to latest to fix local dev setup

- ros/api/v1/hosts.py
- ros/openapi/openapi.json
- tests/test_api_endpoints.py
implement filter by group_name for systems API
https://issues.redhat.com/browse/RHIROS-1158
> RHIROS-1158 implement filter by group for systems API

- ros/lib/config.py
> fix sslmode option for db connection

- pyproject.toml
> Refs #RHIROS-1142 - remove unnecessary sections from pyproject.toml

- ros/api/v1/hosts.py
- ros/openapi/openapi.json
Implement group column sorting for systems API.
[RHIROS-1301](https://issues.redhat.com/browse/RHIROS-1301)
> RHIROS -1301 handle group column sorting

- .github/workflows/build_with_latest_direct_deps.yml
- clowdapp.yaml
- poetry.lock
- pyproject.toml
- ros/api/common/add_group_filter.py
- ros/api/v1/hosts.py
- ros/lib/app.py
- ros/lib/config.py
- ros/lib/feature_flags.py
- tests/test_api_endpoints.py
> Fixes #RHIROS-1269 - feature flags for backend

- ros/api/common/add_group_filter.py
- tests/test_api_endpoints.py
> Load all systems if there are no groups

- ros/lib/constants.py
- ros/lib/utils.py
- tests/data_files/insights-engine-result-idle.json
- tests/data_files/insights-engine-result-no-pcp.json
- tests/data_files/insights-engine-result-optimized.json
- tests/data_files/insights-engine-result-under-pressure.json
- tests/data_files/insights-engine-result-undersized.json
[RHIROS-1315](https://issues.redhat.com/browse/RHIROS-1315)
> RHIROS-1315 process only RHEL systems

- .github/workflows/build_with_latest_direct_deps.yml
- .github/workflows/build_with_latest_indirect_deps.yml
- clowdapp.yaml
- ros/api/common/utils.py
- ros/api/v1/hosts.py
- ros/api/v1/recommendations.py
- ros/lib/app.py
- ros/lib/config.py
- ros/lib/rbac_interface.py
- ros/lib/utils.py
- ros/processor/insights_engine_consumer.py
- tests/test_api_endpoints.py
- Fixing error made on merging leaving extra white spacing.
> Fix added white spaces.

- ros/api/common/add_group_filter.py
- tests/data_files/mock_rbac_returns_array_of_groups_with_null.json
- tests/data_files/mock_rbac_returns_multiple_types_of_read_permissions_with_ungrouped.json
- tests/test_api_endpoints.py
> Refs #RHIROS-1312 - Handle ungrouped systems

- ros/api/common/add_group_filter.py
- ros/api/v1/hosts.py
- ros/lib/app.py
Reverting the unleash usage in backend to get stuff ready for the MVP
> Refs #RHIROS-1269 - revert unleash usage

- ros/lib/app.py
Removing commented code of unleash
> Refs #RHIROS-1269 - clean unleash unused code

- build_deploy.sh
> Add new tag for hotfix branches

- migrations/versions/93262eab7d77_update_top_candidate_and_top_candidate_price_for_existing_records.py
- ros/api/common/instance_types_helper.py
- ros/api/v1/suggested_instance_types.py
> Refs #RHIROS-1231 - don't add double quotes to top_candidate values

- Makefile
> Refs #RHINENG-1098 - remove is_internal key from identity header

- .github/workflows/codeql.yml
> Remove Pipfile.lock refs from codeql.yml

- ros/processor/garbage_collector.py
Logs are not in the correct format
> fix garbage collector log

- Makefile
- ros/api/routes.py
- ros/api/v1/suggested_instance_types.py
- tests/fixtures/db_fixtures.py
- tests/test_api_endpoints.py
The suggested_instance_types api endpoint accepting instance_type with filtering defined on display_name, state and OS
> Fixes #RHIROS-1176, #RHIROS-1178 - suggested_instance_types/<instance_type> api endpoint

- ros/api/v1/suggested_instance_types.py
[RHIROS-1177](https://issues.redhat.com/browse/RHIROS-1177)
> fix suggested instance types filter

- README.md
> Update README as per Python 3.11 changes

- ros/lib/config.py
- ros/lib/consume.py
- ros/lib/produce.py
The platform now has multiple kafka servers, the change is to support new additional servers/all servers
> Fixes #RHINENG-5028 - support multiple kafka servers

- Dockerfile
If we don't have LABELS defined then by default image creation inherits it from parent image which is UBI. This is not acceptable by RHTAP. So defining the LABELS for ROS image.
> Update labels as required for RHTAP

- .gitignore
- scripts/docker-compose.yml
- scripts/xjoin-config/elastic_mapping.json
- scripts/xjoin-config/my-pipeline.json
> Fixes xjoin dev setup

- ros/api/common/utils.py
- ros/lib/utils.py
- tests/test_utils.py
> Fixes #RHINENG-6109 - fetch username for service account

- ros/openapi/openapi.json
> Fixes #RHINENG-8277 - Added server property to openapi json

- Dockerfile
> Fixes #RHINENG-9205 - tag pip to 23.3

- ros/processor/insights_engine_consumer.py
- ros/processor/inventory_events_consumer.py
> Fixes #RHINENG-9532 - precedence should go to org_id

- .tekton/ros-backend-pull-request.yaml
- .tekton/ros-backend-push.yaml
> Build source image everytime

- ros/processor/inventory_events_consumer.py
> #RHINENG-12516 - fix request_id while logging from inventory processor

- clowdapp.yaml
We need to update CPU and Memory params in the Clowdapp file.
This is to ensure we utilize resources on ephemeral environments optimally.
Please include the __context of this change__ here. If the change depends on Kruize add details about that as well!
- If yes what is the version no:
Please check JIRA for additional details.
> RHINENG-12214 Update CPU and Memory Param names

- ros/processor/renovate.json
> Hook for triggering the Konflux build

- clowdapp.yaml
> Update clowdapp to use konflux builds

- build_deploy.sh
Include the `pcp-zeroconf` branch for image building.
> RHINENG-14338 update build file to include pcp-zeroconf branch

- poetry.lock
- pyproject.toml
> Fixes #RHINENG-14909 - Update insights-core and pytest packages

- .gitignore
- ros/lib/config.py
- ros/processor/main.py
- ros/processor/suggestions_engine.py
Server setup for Suggestions Engine (renamed from PCP Generator).
> RHINENG-13972 suggestions engine server setup

- ros/lib/config.py
- ros/lib/consume.py
- ros/processor/insights_engine_consumer.py
- ros/processor/inventory_events_consumer.py
Refactor `init_consumer` to include a different `group.id`.
> RHINENG-15095 Refactor init_consumer function

- Dockerfile
Resolves - [https://issues.redhat.com/browse/RHINENG-12541](RHINENG-12541)
> RHINENG-12541 Migrate UBi8-min to UBi9-min

- poetry.lock
> Fixes #RHINENG-16067 - update poetry.lock file for package updates

- scripts/docker-compose.yml
[RHINENG-16278](https://issues.redhat.com/browse/RHINENG-16278)
> RHINENG-16278 add ros.events topic to docker-compose.yml

- Makefile
Update Makefile commands to include new commands for local development
> Updated Makefile with new commands for local development
